spring:
  application:
    name: GatewayService

server:
  servlet:
    context-path: /
  port: 8765

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true