server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wastedb-prod
    username: wastedbAdminProd
    password: secureWastedbAdminProd
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
