server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:addressdb-dev;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
