server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/addressdb-prod
    username: addressdbAdminProd
    password: secureAddressdbAdminProd
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
